// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: microtick/v1beta1/msg/TxUpdate.proto

package msg

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type TxUpdateQuote struct {
	Id        uint32                                        `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	Requester github_com_cosmos_cosmos_sdk_types.AccAddress `protobuf:"bytes,2,opt,name=requester,proto3,casttype=github.com/cosmos/cosmos-sdk/types.AccAddress" json:"requester"`
	NewSpot   string                                        `protobuf:"bytes,3,opt,name=new_spot,json=newSpot,proto3" json:"new_spot"`
	NewAsk    string                                        `protobuf:"bytes,4,opt,name=new_ask,json=newAsk,proto3" json:"new_ask"`
	NewBid    string                                        `protobuf:"bytes,5,opt,name=new_bid,json=newBid,proto3" json:"new_bid"`
}

func (m *TxUpdateQuote) Reset()         { *m = TxUpdateQuote{} }
func (m *TxUpdateQuote) String() string { return proto.CompactTextString(m) }
func (*TxUpdateQuote) ProtoMessage()    {}
func (*TxUpdateQuote) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef75ed2b8495314c, []int{0}
}
func (m *TxUpdateQuote) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TxUpdateQuote) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TxUpdateQuote.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TxUpdateQuote) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxUpdateQuote.Merge(m, src)
}
func (m *TxUpdateQuote) XXX_Size() int {
	return m.Size()
}
func (m *TxUpdateQuote) XXX_DiscardUnknown() {
	xxx_messageInfo_TxUpdateQuote.DiscardUnknown(m)
}

var xxx_messageInfo_TxUpdateQuote proto.InternalMessageInfo

func (m *TxUpdateQuote) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *TxUpdateQuote) GetRequester() github_com_cosmos_cosmos_sdk_types.AccAddress {
	if m != nil {
		return m.Requester
	}
	return nil
}

func (m *TxUpdateQuote) GetNewSpot() string {
	if m != nil {
		return m.NewSpot
	}
	return ""
}

func (m *TxUpdateQuote) GetNewAsk() string {
	if m != nil {
		return m.NewAsk
	}
	return ""
}

func (m *TxUpdateQuote) GetNewBid() string {
	if m != nil {
		return m.NewBid
	}
	return ""
}

type UpdateQuoteData struct {
	Time       int64         `protobuf:"varint,1,opt,name=time,proto3" json:"time"`
	Market     string        `protobuf:"bytes,2,opt,name=market,proto3" json:"market"`
	Duration   string        `protobuf:"bytes,3,opt,name=duration,proto3" json:"duration"`
	Consensus  types.DecCoin `protobuf:"bytes,4,opt,name=consensus,proto3" json:"consensus"`
	Commission types.DecCoin `protobuf:"bytes,5,opt,name=commission,proto3" json:"commission"`
	Reward     types.Coin    `protobuf:"bytes,6,opt,name=reward,proto3" json:"reward"`
	Adjustment string        `protobuf:"bytes,7,opt,name=adjustment,proto3" json:"adjustment"`
}

func (m *UpdateQuoteData) Reset()         { *m = UpdateQuoteData{} }
func (m *UpdateQuoteData) String() string { return proto.CompactTextString(m) }
func (*UpdateQuoteData) ProtoMessage()    {}
func (*UpdateQuoteData) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef75ed2b8495314c, []int{1}
}
func (m *UpdateQuoteData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *UpdateQuoteData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_UpdateQuoteData.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *UpdateQuoteData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateQuoteData.Merge(m, src)
}
func (m *UpdateQuoteData) XXX_Size() int {
	return m.Size()
}
func (m *UpdateQuoteData) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateQuoteData.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateQuoteData proto.InternalMessageInfo

func (m *UpdateQuoteData) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *UpdateQuoteData) GetMarket() string {
	if m != nil {
		return m.Market
	}
	return ""
}

func (m *UpdateQuoteData) GetDuration() string {
	if m != nil {
		return m.Duration
	}
	return ""
}

func (m *UpdateQuoteData) GetConsensus() types.DecCoin {
	if m != nil {
		return m.Consensus
	}
	return types.DecCoin{}
}

func (m *UpdateQuoteData) GetCommission() types.DecCoin {
	if m != nil {
		return m.Commission
	}
	return types.DecCoin{}
}

func (m *UpdateQuoteData) GetReward() types.Coin {
	if m != nil {
		return m.Reward
	}
	return types.Coin{}
}

func (m *UpdateQuoteData) GetAdjustment() string {
	if m != nil {
		return m.Adjustment
	}
	return ""
}

func init() {
	proto.RegisterType((*TxUpdateQuote)(nil), "microtick.v1beta1.msg.TxUpdateQuote")
	proto.RegisterType((*UpdateQuoteData)(nil), "microtick.v1beta1.msg.UpdateQuoteData")
}

func init() {
	proto.RegisterFile("microtick/v1beta1/msg/TxUpdate.proto", fileDescriptor_ef75ed2b8495314c)
}

var fileDescriptor_ef75ed2b8495314c = []byte{
	// 502 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x8d, 0x93, 0xd6, 0x4d, 0xb6, 0x1f, 0x88, 0x15, 0x20, 0x53, 0x55, 0x76, 0x14, 0x55, 0x22,
	0x12, 0xaa, 0xad, 0xc2, 0x1d, 0x29, 0xa6, 0x1c, 0x91, 0x60, 0x81, 0x0b, 0x42, 0xaa, 0x6c, 0xef,
	0xca, 0x2c, 0xd1, 0xee, 0x06, 0xcf, 0x9a, 0x14, 0x7e, 0x05, 0xfc, 0xab, 0x1e, 0x7b, 0xe4, 0x64,
	0xa1, 0xe4, 0xe6, 0x9f, 0xd0, 0x13, 0xf2, 0xc6, 0xb1, 0x8d, 0xc4, 0xa1, 0x17, 0xcf, 0xf3, 0xf3,
	0x9b, 0x37, 0x9a, 0xb7, 0x6b, 0x74, 0x2a, 0x78, 0x92, 0x29, 0xcd, 0x93, 0x79, 0xf0, 0xed, 0x3c,
	0x66, 0x3a, 0x3a, 0x0f, 0x04, 0xa4, 0xc1, 0xfb, 0xab, 0x0f, 0x0b, 0x1a, 0x69, 0xe6, 0x2f, 0x32,
	0xa5, 0x15, 0x7e, 0xd8, 0xa8, 0xfc, 0x5a, 0xe5, 0x0b, 0x48, 0x8f, 0x1f, 0xa4, 0x2a, 0x55, 0x46,
	0x11, 0x54, 0x68, 0x23, 0x3e, 0x76, 0x13, 0x05, 0x42, 0x41, 0x10, 0x47, 0xc0, 0x1a, 0xd3, 0x44,
	0x71, 0xb9, 0xf9, 0x3e, 0xb9, 0xb5, 0xd0, 0xe1, 0xd6, 0xff, 0x6d, 0xae, 0x34, 0xc3, 0x8f, 0x50,
	0x9f, 0x53, 0xc7, 0x1a, 0x5b, 0xd3, 0xc3, 0xd0, 0x2e, 0x0b, 0xaf, 0xcf, 0x29, 0xe9, 0x73, 0x8a,
	0x3f, 0xa1, 0x51, 0xc6, 0xbe, 0xe6, 0x0c, 0x34, 0xcb, 0x9c, 0xfe, 0xd8, 0x9a, 0x1e, 0x84, 0x2f,
	0xca, 0xc2, 0x6b, 0xc9, 0xdb, 0xc2, 0x3b, 0x4b, 0xb9, 0xfe, 0x9c, 0xc7, 0x7e, 0xa2, 0x44, 0x50,
	0x0f, 0xde, 0x94, 0x33, 0xa0, 0xf3, 0x40, 0x7f, 0x5f, 0x30, 0xf0, 0x67, 0x49, 0x32, 0xa3, 0x34,
	0x63, 0x00, 0xa4, 0xed, 0xc5, 0x4f, 0xd0, 0x50, 0xb2, 0xe5, 0x25, 0x2c, 0x94, 0x76, 0x06, 0x63,
	0x6b, 0x3a, 0x0a, 0x0f, 0xca, 0xc2, 0x6b, 0x38, 0xb2, 0x27, 0xd9, 0xf2, 0xdd, 0x42, 0x69, 0x7c,
	0x8a, 0x2a, 0x78, 0x19, 0xc1, 0xdc, 0xd9, 0x31, 0xba, 0xfd, 0xb2, 0xf0, 0xb6, 0x14, 0xb1, 0x25,
	0x5b, 0xce, 0x60, 0xbe, 0x55, 0xc5, 0x9c, 0x3a, 0xbb, 0xff, 0xaa, 0x62, 0x4e, 0x8d, 0x2a, 0xe4,
	0x74, 0xf2, 0x6b, 0x80, 0xee, 0x75, 0x56, 0xbf, 0x88, 0x74, 0x84, 0x4f, 0xd0, 0x8e, 0xe6, 0x82,
	0x99, 0x00, 0x06, 0xe1, 0xb0, 0x2c, 0x3c, 0xf3, 0x4e, 0xcc, 0x13, 0x4f, 0x90, 0x2d, 0xa2, 0x6c,
	0xce, 0xb4, 0x49, 0x60, 0x14, 0xa2, 0xb2, 0xf0, 0x6a, 0x86, 0xd4, 0x15, 0x4f, 0xd1, 0x90, 0xe6,
	0x59, 0xa4, 0xb9, 0x92, 0xdd, 0x55, 0xb6, 0x1c, 0x69, 0x10, 0x7e, 0x8d, 0x46, 0x89, 0x92, 0xc0,
	0x24, 0xe4, 0x60, 0xb6, 0xd9, 0x7f, 0x76, 0xe2, 0x6f, 0x02, 0xf3, 0xab, 0x03, 0x6b, 0xce, 0xf7,
	0x82, 0x25, 0x2f, 0x15, 0x97, 0xe1, 0xfd, 0xeb, 0xc2, 0xeb, 0x55, 0xa1, 0x37, 0x6d, 0xa4, 0x85,
	0xf8, 0x0d, 0x42, 0x89, 0x12, 0x82, 0x03, 0x54, 0xa3, 0x77, 0xef, 0xe0, 0x87, 0x6b, 0xbf, 0x4e,
	0x1f, 0xe9, 0x60, 0x3c, 0x43, 0x76, 0xc6, 0x96, 0x51, 0x46, 0x1d, 0xdb, 0xb8, 0x3d, 0xfe, 0xaf,
	0x9b, 0xb1, 0x3a, 0xaa, 0xad, 0xea, 0x06, 0x52, 0x57, 0xec, 0x23, 0x14, 0xd1, 0x2f, 0x39, 0x68,
	0xc1, 0xa4, 0x76, 0xf6, 0x4c, 0x1e, 0x47, 0xd5, 0xc8, 0x96, 0x25, 0x1d, 0x1c, 0xbe, 0xba, 0x5e,
	0xb9, 0xd6, 0xcd, 0xca, 0xb5, 0xfe, 0xac, 0x5c, 0xeb, 0xe7, 0xda, 0xed, 0xdd, 0xac, 0xdd, 0xde,
	0xef, 0xb5, 0xdb, 0xfb, 0xf8, 0xb4, 0x73, 0xb9, 0xda, 0x1f, 0x45, 0xe8, 0x1f, 0x4a, 0xb2, 0xe0,
	0xaa, 0x4b, 0x41, 0x1a, 0xdb, 0xe6, 0x7a, 0x3f, 0xff, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x6f, 0x8a,
	0xa3, 0x16, 0x53, 0x03, 0x00, 0x00,
}

func (m *TxUpdateQuote) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TxUpdateQuote) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TxUpdateQuote) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.NewBid) > 0 {
		i -= len(m.NewBid)
		copy(dAtA[i:], m.NewBid)
		i = encodeVarintTxUpdate(dAtA, i, uint64(len(m.NewBid)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.NewAsk) > 0 {
		i -= len(m.NewAsk)
		copy(dAtA[i:], m.NewAsk)
		i = encodeVarintTxUpdate(dAtA, i, uint64(len(m.NewAsk)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.NewSpot) > 0 {
		i -= len(m.NewSpot)
		copy(dAtA[i:], m.NewSpot)
		i = encodeVarintTxUpdate(dAtA, i, uint64(len(m.NewSpot)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Requester) > 0 {
		i -= len(m.Requester)
		copy(dAtA[i:], m.Requester)
		i = encodeVarintTxUpdate(dAtA, i, uint64(len(m.Requester)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintTxUpdate(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *UpdateQuoteData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *UpdateQuoteData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *UpdateQuoteData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Adjustment) > 0 {
		i -= len(m.Adjustment)
		copy(dAtA[i:], m.Adjustment)
		i = encodeVarintTxUpdate(dAtA, i, uint64(len(m.Adjustment)))
		i--
		dAtA[i] = 0x3a
	}
	{
		size, err := m.Reward.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTxUpdate(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	{
		size, err := m.Commission.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTxUpdate(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	{
		size, err := m.Consensus.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTxUpdate(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if len(m.Duration) > 0 {
		i -= len(m.Duration)
		copy(dAtA[i:], m.Duration)
		i = encodeVarintTxUpdate(dAtA, i, uint64(len(m.Duration)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Market) > 0 {
		i -= len(m.Market)
		copy(dAtA[i:], m.Market)
		i = encodeVarintTxUpdate(dAtA, i, uint64(len(m.Market)))
		i--
		dAtA[i] = 0x12
	}
	if m.Time != 0 {
		i = encodeVarintTxUpdate(dAtA, i, uint64(m.Time))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintTxUpdate(dAtA []byte, offset int, v uint64) int {
	offset -= sovTxUpdate(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *TxUpdateQuote) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovTxUpdate(uint64(m.Id))
	}
	l = len(m.Requester)
	if l > 0 {
		n += 1 + l + sovTxUpdate(uint64(l))
	}
	l = len(m.NewSpot)
	if l > 0 {
		n += 1 + l + sovTxUpdate(uint64(l))
	}
	l = len(m.NewAsk)
	if l > 0 {
		n += 1 + l + sovTxUpdate(uint64(l))
	}
	l = len(m.NewBid)
	if l > 0 {
		n += 1 + l + sovTxUpdate(uint64(l))
	}
	return n
}

func (m *UpdateQuoteData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Time != 0 {
		n += 1 + sovTxUpdate(uint64(m.Time))
	}
	l = len(m.Market)
	if l > 0 {
		n += 1 + l + sovTxUpdate(uint64(l))
	}
	l = len(m.Duration)
	if l > 0 {
		n += 1 + l + sovTxUpdate(uint64(l))
	}
	l = m.Consensus.Size()
	n += 1 + l + sovTxUpdate(uint64(l))
	l = m.Commission.Size()
	n += 1 + l + sovTxUpdate(uint64(l))
	l = m.Reward.Size()
	n += 1 + l + sovTxUpdate(uint64(l))
	l = len(m.Adjustment)
	if l > 0 {
		n += 1 + l + sovTxUpdate(uint64(l))
	}
	return n
}

func sovTxUpdate(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTxUpdate(x uint64) (n int) {
	return sovTxUpdate(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *TxUpdateQuote) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTxUpdate
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TxUpdateQuote: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TxUpdateQuote: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTxUpdate
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Requester", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTxUpdate
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTxUpdate
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTxUpdate
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Requester = append(m.Requester[:0], dAtA[iNdEx:postIndex]...)
			if m.Requester == nil {
				m.Requester = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NewSpot", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTxUpdate
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTxUpdate
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTxUpdate
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NewSpot = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NewAsk", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTxUpdate
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTxUpdate
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTxUpdate
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NewAsk = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NewBid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTxUpdate
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTxUpdate
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTxUpdate
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NewBid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTxUpdate(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTxUpdate
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *UpdateQuoteData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTxUpdate
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: UpdateQuoteData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: UpdateQuoteData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Time", wireType)
			}
			m.Time = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTxUpdate
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Time |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Market", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTxUpdate
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTxUpdate
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTxUpdate
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Market = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Duration", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTxUpdate
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTxUpdate
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTxUpdate
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Duration = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Consensus", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTxUpdate
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTxUpdate
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTxUpdate
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Consensus.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Commission", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTxUpdate
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTxUpdate
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTxUpdate
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Commission.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reward", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTxUpdate
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTxUpdate
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTxUpdate
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Reward.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Adjustment", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTxUpdate
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTxUpdate
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTxUpdate
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Adjustment = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTxUpdate(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTxUpdate
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTxUpdate(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTxUpdate
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTxUpdate
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTxUpdate
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTxUpdate
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTxUpdate
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTxUpdate
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTxUpdate        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTxUpdate          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTxUpdate = fmt.Errorf("proto: unexpected end of group")
)
